apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: feature-backend-app-secret
  namespace: default
spec:
  encryptedData:
    ALLOW_ORIGINS: AgAqXLXXygp+GGOi4kdRL3EpH/4gSqeQ8OnMelPgwE4iZSBW18QlBuOXeyLig6TMajTU5hzahgOj9+gqCI6M2aQFSVjUj/Zif4DA1d5V38vWPk0QXSyGeSX6Uulmy1
    SQLALCHEMY_DATABASE_URL: AgCp2aG7njPC3xg6v+SnrPyaJu02sG2Pk/Iu/WHuIRPgOXpNqfLM3urb5oi2v2VpVrpdD80zMYk8BNVTjf5VKl+Ldr/nr/i0kHpWTQTyEVDe8v8oLdc8
  template:
    metadata:
      creationTimestamp: null
      name: feature-backend-app-secret
      namespace: default
