apiVersion: v1
data:
  ALLOW_ORIGINS: aHR0cDovL2FwcC50aW1lcGFzcy54eXov
  SQLALCHEMY_DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnR0TkxMdHNmQ0xqYmhZM0pAbWFpbi1wb3N0Z3Jlcy5jbG84MnFjeTg2Nm4uZXUtY2VudHJhbC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvZGVmYXVsdGRi
kind: Secret
metadata:
  creationTimestamp: null
  name: feature-backend-app-secret
