apiVersion: v1
kind: Service
metadata:
  name: feature-frontend-svc
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: feature-app-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
